/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "uart_tx.v:1.1-147.10" *)
module uart_tx(clk, reset, tx_data, tx_start, tx_busy, tx);
  (* src = "uart_tx.v:72.1-117.4" *)
  wire [15:0] _000_;
  (* src = "uart_tx.v:72.1-117.4" *)
  wire [2:0] _001_;
  (* src = "uart_tx.v:72.1-117.4" *)
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* src = "uart_tx.v:30.15-30.27" *)
  reg [15:0] baud_counter;
  (* src = "uart_tx.v:31.14-31.25" *)
  reg [2:0] bit_counter;
  (* src = "uart_tx.v:4.16-4.19" *)
  input clk;
  wire clk;
  (* src = "uart_tx.v:25.13-25.21" *)
  reg [7:0] data_reg;
  (* src = "uart_tx.v:21.21-21.31" *)
  wire [1:0] next_state;
  (* src = "uart_tx.v:5.15-5.20" *)
  input reset;
  wire reset;
  (* src = "uart_tx.v:26.13-26.22" *)
  reg [7:0] shift_reg;
  (* src = "uart_tx.v:21.13-21.18" *)
  reg [1:0] state;
  (* src = "uart_tx.v:11.14-11.16" *)
  output tx;
  wire tx;
  (* src = "uart_tx.v:10.14-10.21" *)
  output tx_busy;
  wire tx_busy;
  (* src = "uart_tx.v:6.23-6.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "uart_tx.v:7.15-7.23" *)
  input tx_start;
  wire tx_start;
  assign _076_ = baud_counter[0] & ~(baud_counter[1]);
  assign _077_ = baud_counter[3] | baud_counter[2];
  assign _078_ = _076_ & ~(_077_);
  assign _079_ = ~(baud_counter[5] & baud_counter[4]);
  assign _080_ = baud_counter[6] | ~(baud_counter[7]);
  assign _081_ = _080_ | _079_;
  assign _082_ = _078_ & ~(_081_);
  assign _083_ = baud_counter[9] | ~(baud_counter[8]);
  assign _084_ = baud_counter[11] | baud_counter[10];
  assign _085_ = _084_ | _083_;
  assign _086_ = baud_counter[13] | baud_counter[12];
  assign _087_ = baud_counter[15] | baud_counter[14];
  assign _088_ = _087_ | _086_;
  assign _089_ = _088_ | _085_;
  assign _090_ = _082_ & ~(_089_);
  assign _091_ = ~(state[1] & state[0]);
  assign _092_ = ~(_091_ | _090_);
  assign _093_ = state[1] | ~(state[0]);
  assign _094_ = _093_ | _090_;
  assign _095_ = _094_ & ~(_092_);
  assign _096_ = ~(bit_counter[1] & bit_counter[0]);
  assign _097_ = _096_ | ~(bit_counter[2]);
  assign _098_ = _097_ | ~(_090_);
  assign _099_ = state[1] & ~(state[0]);
  assign _100_ = _099_ & _098_;
  assign _101_ = state[1] | state[0];
  assign _007_ = ~(_101_ | tx_start);
  assign _008_ = _007_ | _100_;
  assign _003_ = _095_ & ~(_008_);
  assign _004_ = tx_start & ~(_101_);
  assign _009_ = _099_ & ~(_090_);
  assign _010_ = _094_ & ~(_009_);
  assign _011_ = ~_098_;
  assign _012_ = _099_ ? _011_ : _093_;
  assign _005_ = _010_ & ~(_012_);
  assign _013_ = ~(state[1] | state[0]);
  assign tx_busy = ~_013_;
  assign _014_ = _098_ | ~(_099_);
  assign _015_ = ~_090_;
  assign _016_ = _099_ ? _015_ : _101_;
  assign _006_ = _014_ & ~(_016_);
  assign _017_ = _090_ | baud_counter[0];
  assign _000_[0] = tx_busy & ~(_017_);
  assign _018_ = ~(baud_counter[1] ^ baud_counter[0]);
  assign _019_ = _018_ | _090_;
  assign _000_[1] = tx_busy & ~(_019_);
  assign _020_ = ~(baud_counter[1] & baud_counter[0]);
  assign _021_ = _020_ ^ baud_counter[2];
  assign _022_ = _021_ | _090_;
  assign _000_[2] = tx_busy & ~(_022_);
  assign _023_ = _020_ | ~(baud_counter[2]);
  assign _024_ = _023_ ^ baud_counter[3];
  assign _025_ = _024_ | _090_;
  assign _000_[3] = tx_busy & ~(_025_);
  assign _026_ = ~(baud_counter[3] & baud_counter[2]);
  assign _027_ = _026_ | _020_;
  assign _028_ = _027_ ^ baud_counter[4];
  assign _029_ = _028_ | _090_;
  assign _000_[4] = tx_busy & ~(_029_);
  assign _030_ = _027_ | ~(baud_counter[4]);
  assign _031_ = _030_ ^ baud_counter[5];
  assign _032_ = _031_ | _090_;
  assign _000_[5] = tx_busy & ~(_032_);
  assign _033_ = _027_ | _079_;
  assign _034_ = _033_ ^ baud_counter[6];
  assign _035_ = _034_ | _090_;
  assign _000_[6] = tx_busy & ~(_035_);
  assign _036_ = _033_ | ~(baud_counter[6]);
  assign _037_ = _036_ ^ baud_counter[7];
  assign _038_ = _037_ | _090_;
  assign _000_[7] = tx_busy & ~(_038_);
  assign _039_ = ~(baud_counter[7] & baud_counter[6]);
  assign _040_ = _039_ | _079_;
  assign _041_ = _040_ | _027_;
  assign _042_ = _041_ ^ baud_counter[8];
  assign _043_ = _042_ | _090_;
  assign _000_[8] = tx_busy & ~(_043_);
  assign _044_ = ~(_040_ | _027_);
  assign _045_ = ~(_044_ & baud_counter[8]);
  assign _046_ = _045_ ^ baud_counter[9];
  assign _047_ = _046_ | _090_;
  assign _000_[9] = tx_busy & ~(_047_);
  assign _048_ = ~(baud_counter[8] & baud_counter[9]);
  assign _049_ = _048_ | _041_;
  assign _050_ = _049_ ^ baud_counter[10];
  assign _051_ = _050_ | _090_;
  assign _000_[10] = tx_busy & ~(_051_);
  assign _052_ = _049_ | ~(baud_counter[10]);
  assign _053_ = _052_ ^ baud_counter[11];
  assign _054_ = _053_ | _090_;
  assign _000_[11] = tx_busy & ~(_054_);
  assign _055_ = ~(baud_counter[11] & baud_counter[10]);
  assign _056_ = _055_ | _048_;
  assign _057_ = _056_ | _041_;
  assign _058_ = _057_ ^ baud_counter[12];
  assign _059_ = _058_ | _090_;
  assign _000_[12] = tx_busy & ~(_059_);
  assign _060_ = _057_ | ~(baud_counter[12]);
  assign _061_ = _060_ ^ baud_counter[13];
  assign _062_ = _061_ | _090_;
  assign _000_[13] = tx_busy & ~(_062_);
  assign _063_ = ~(baud_counter[13] & baud_counter[12]);
  assign _064_ = _063_ | _057_;
  assign _065_ = _064_ ^ baud_counter[14];
  assign _066_ = _065_ | _090_;
  assign _000_[14] = tx_busy & ~(_066_);
  assign _067_ = _064_ | ~(baud_counter[14]);
  assign _068_ = _067_ ^ baud_counter[15];
  assign _069_ = _068_ | _090_;
  assign _000_[15] = tx_busy & ~(_069_);
  assign _001_[0] = _099_ & ~(bit_counter[0]);
  assign _070_ = ~(bit_counter[1] ^ bit_counter[0]);
  assign _001_[1] = _099_ & ~(_070_);
  assign _071_ = _096_ ^ bit_counter[2];
  assign _001_[2] = _099_ & ~(_071_);
  assign _002_[0] = _099_ ? shift_reg[1] : data_reg[0];
  assign _002_[1] = _099_ ? shift_reg[2] : data_reg[1];
  assign _002_[2] = _099_ ? shift_reg[3] : data_reg[2];
  assign _002_[3] = _099_ ? shift_reg[4] : data_reg[3];
  assign _002_[4] = _099_ ? shift_reg[5] : data_reg[4];
  assign _002_[5] = _099_ ? shift_reg[6] : data_reg[5];
  assign _002_[6] = _099_ ? shift_reg[7] : data_reg[6];
  assign _002_[7] = data_reg[7] & ~(_099_);
  assign _072_ = ~(_101_ & _091_);
  assign _073_ = _099_ & shift_reg[0];
  assign _074_ = _073_ | _072_;
  assign _075_ = state[0] & ~(state[1]);
  assign tx = _074_ & ~(_075_);
  assign next_state[0] = _013_ | _099_;
  assign next_state[1] = state[1] ^ state[0];
  (* src = "uart_tx.v:36.1-42.4" *)
  always @(posedge clk, posedge reset)
    if (reset) state[0] <= 1'h0;
    else if (_003_) state[0] <= next_state[0];
  (* src = "uart_tx.v:36.1-42.4" *)
  always @(posedge clk, posedge reset)
    if (reset) state[1] <= 1'h0;
    else if (_003_) state[1] <= next_state[1];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[0] <= 1'h0;
    else if (_005_) shift_reg[0] <= _002_[0];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[1] <= 1'h0;
    else if (_005_) shift_reg[1] <= _002_[1];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[2] <= 1'h0;
    else if (_005_) shift_reg[2] <= _002_[2];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[3] <= 1'h0;
    else if (_005_) shift_reg[3] <= _002_[3];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[4] <= 1'h0;
    else if (_005_) shift_reg[4] <= _002_[4];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[5] <= 1'h0;
    else if (_005_) shift_reg[5] <= _002_[5];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[6] <= 1'h0;
    else if (_005_) shift_reg[6] <= _002_[6];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) shift_reg[7] <= 1'h0;
    else if (_005_) shift_reg[7] <= _002_[7];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) bit_counter[0] <= 1'h0;
    else if (_006_) bit_counter[0] <= _001_[0];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) bit_counter[1] <= 1'h0;
    else if (_006_) bit_counter[1] <= _001_[1];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) bit_counter[2] <= 1'h0;
    else if (_006_) bit_counter[2] <= _001_[2];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[0] <= 1'h0;
    else baud_counter[0] <= _000_[0];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[1] <= 1'h0;
    else baud_counter[1] <= _000_[1];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[2] <= 1'h0;
    else baud_counter[2] <= _000_[2];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[3] <= 1'h0;
    else baud_counter[3] <= _000_[3];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[4] <= 1'h0;
    else baud_counter[4] <= _000_[4];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[5] <= 1'h0;
    else baud_counter[5] <= _000_[5];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[6] <= 1'h0;
    else baud_counter[6] <= _000_[6];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[7] <= 1'h0;
    else baud_counter[7] <= _000_[7];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[8] <= 1'h0;
    else baud_counter[8] <= _000_[8];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[9] <= 1'h0;
    else baud_counter[9] <= _000_[9];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[10] <= 1'h0;
    else baud_counter[10] <= _000_[10];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[11] <= 1'h0;
    else baud_counter[11] <= _000_[11];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[12] <= 1'h0;
    else baud_counter[12] <= _000_[12];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[13] <= 1'h0;
    else baud_counter[13] <= _000_[13];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[14] <= 1'h0;
    else baud_counter[14] <= _000_[14];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) baud_counter[15] <= 1'h0;
    else baud_counter[15] <= _000_[15];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[0] <= 1'h0;
    else if (_004_) data_reg[0] <= tx_data[0];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[1] <= 1'h0;
    else if (_004_) data_reg[1] <= tx_data[1];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[2] <= 1'h0;
    else if (_004_) data_reg[2] <= tx_data[2];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[3] <= 1'h0;
    else if (_004_) data_reg[3] <= tx_data[3];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[4] <= 1'h0;
    else if (_004_) data_reg[4] <= tx_data[4];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[5] <= 1'h0;
    else if (_004_) data_reg[5] <= tx_data[5];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[6] <= 1'h0;
    else if (_004_) data_reg[6] <= tx_data[6];
  (* src = "uart_tx.v:72.1-117.4" *)
  always @(posedge clk, posedge reset)
    if (reset) data_reg[7] <= 1'h0;
    else if (_004_) data_reg[7] <= tx_data[7];
endmodule
