/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "Washing_Mac_moore.v:1.1-136.10" *)
module Washing_Mac_moore(clk, reset, start, water_fill, wash_done, drain_done, spin_done, door_open, temp_high, temp_critical, done_timer_out, water_valve, wash_motor, drain_pump, spin_motor, heater, done, current_state);
  (* src = "Washing_Mac_moore.v:103.17-103.115" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  (* src = "Washing_Mac_moore.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "Washing_Mac_moore.v:22.22-22.35" *)
  output [2:0] current_state;
  reg [2:0] current_state;
  (* src = "Washing_Mac_moore.v:21.16-21.20" *)
  output done;
  wire done;
  (* src = "Washing_Mac_moore.v:13.12-13.26" *)
  input done_timer_out;
  wire done_timer_out;
  (* src = "Washing_Mac_moore.v:10.12-10.21" *)
  input door_open;
  wire door_open;
  (* src = "Washing_Mac_moore.v:8.12-8.22" *)
  input drain_done;
  wire drain_done;
  (* src = "Washing_Mac_moore.v:18.16-18.26" *)
  output drain_pump;
  wire drain_pump;
  (* src = "Washing_Mac_moore.v:20.16-20.22" *)
  output heater;
  wire heater;
  (* src = "Washing_Mac_moore.v:35.15-35.25" *)
  wire [2:0] next_state;
  (* src = "Washing_Mac_moore.v:36.15-36.29" *)
  reg [2:0] previous_state;
  (* src = "Washing_Mac_moore.v:4.12-4.17" *)
  input reset;
  wire reset;
  (* src = "Washing_Mac_moore.v:9.12-9.21" *)
  input spin_done;
  wire spin_done;
  (* src = "Washing_Mac_moore.v:19.16-19.26" *)
  output spin_motor;
  wire spin_motor;
  (* src = "Washing_Mac_moore.v:5.12-5.17" *)
  input start;
  wire start;
  (* src = "Washing_Mac_moore.v:12.12-12.25" *)
  input temp_critical;
  wire temp_critical;
  (* src = "Washing_Mac_moore.v:11.12-11.21" *)
  input temp_high;
  wire temp_high;
  (* src = "Washing_Mac_moore.v:7.12-7.21" *)
  input wash_done;
  wire wash_done;
  (* src = "Washing_Mac_moore.v:17.16-17.26" *)
  output wash_motor;
  wire wash_motor;
  (* src = "Washing_Mac_moore.v:6.12-6.22" *)
  input water_fill;
  wire water_fill;
  (* src = "Washing_Mac_moore.v:16.16-16.27" *)
  output water_valve;
  wire water_valve;
  assign _052_ = start & ~(door_open);
  assign _053_ = current_state[2] & ~(_052_);
  assign _054_ = ~current_state[2];
  assign _055_ = ~(current_state[0] & current_state[1]);
  assign _056_ = _055_ | _054_;
  assign _057_ = current_state[0] | ~(current_state[1]);
  assign _058_ = current_state[2] & ~(_057_);
  assign _059_ = _056_ & ~(_058_);
  assign _060_ = current_state[1] | ~(current_state[0]);
  assign _061_ = current_state[2] & ~(_060_);
  assign _062_ = current_state[0] | current_state[1];
  assign _063_ = current_state[2] & ~(_062_);
  assign _064_ = _063_ | _061_;
  assign _065_ = _059_ & ~(_064_);
  assign _066_ = _054_ & ~(_060_);
  assign _067_ = _054_ & ~(_055_);
  assign _068_ = _054_ & ~(_057_);
  assign _069_ = _068_ | _067_;
  assign _070_ = _069_ | _066_;
  assign _071_ = _065_ & ~(_070_);
  assign _072_ = ~previous_state[2];
  assign _073_ = temp_critical ? _054_ : _072_;
  assign _074_ = ~(_073_ | _056_);
  assign _075_ = door_open ? _054_ : _072_;
  assign _076_ = _058_ & ~(_075_);
  assign _077_ = _076_ | _074_;
  assign _078_ = done_timer_out & door_open;
  assign _079_ = _061_ & ~(_078_);
  assign _080_ = ~temp_critical;
  assign _081_ = spin_done | current_state[2];
  assign _082_ = _081_ | door_open;
  assign _083_ = _080_ & ~(_082_);
  assign _084_ = _063_ & ~(_083_);
  assign _085_ = _084_ | _079_;
  assign _086_ = _085_ | _077_;
  assign _087_ = drain_done | current_state[2];
  assign _088_ = _087_ | door_open;
  assign _089_ = _080_ & ~(_088_);
  assign _090_ = _067_ & ~(_089_);
  assign _091_ = current_state[2] & ~(wash_done);
  assign _092_ = _091_ | door_open;
  assign _093_ = _080_ & ~(_092_);
  assign _094_ = _068_ & ~(_093_);
  assign _095_ = _094_ | _090_;
  assign _096_ = current_state[2] & ~(water_fill);
  assign _097_ = _096_ | door_open;
  assign _098_ = _080_ & ~(_097_);
  assign _099_ = _066_ & ~(_098_);
  assign _100_ = _099_ | _095_;
  assign _101_ = _100_ | _086_;
  assign next_state[2] = _071_ ? _053_ : _101_;
  assign _102_ = _052_ | current_state[0];
  assign _103_ = ~current_state[0];
  assign _104_ = ~previous_state[0];
  assign _105_ = temp_critical ? _103_ : _104_;
  assign _106_ = ~(_105_ | _056_);
  assign _107_ = door_open ? _103_ : _104_;
  assign _108_ = _058_ & ~(_107_);
  assign _109_ = _108_ | _106_;
  assign _110_ = ~door_open;
  assign _111_ = ~(spin_done | current_state[0]);
  assign _112_ = _110_ & ~(_111_);
  assign _113_ = _080_ & ~(_112_);
  assign _114_ = _063_ & ~(_113_);
  assign _115_ = _114_ | _079_;
  assign _116_ = _115_ | _109_;
  assign _117_ = drain_done | ~(current_state[0]);
  assign _118_ = _110_ & ~(_117_);
  assign _119_ = _080_ & ~(_118_);
  assign _120_ = _067_ & ~(_119_);
  assign _121_ = ~(wash_done | current_state[0]);
  assign _122_ = _110_ & ~(_121_);
  assign _123_ = _080_ & ~(_122_);
  assign _124_ = _068_ & ~(_123_);
  assign _001_ = _124_ | _120_;
  assign _002_ = water_fill | ~(current_state[0]);
  assign _003_ = _110_ & ~(_002_);
  assign _004_ = _080_ & ~(_003_);
  assign _005_ = _066_ & ~(_004_);
  assign _006_ = _005_ | _001_;
  assign _007_ = _006_ | _116_;
  assign next_state[0] = _071_ ? _102_ : _007_;
  assign _008_ = current_state[1] & ~(_052_);
  assign _009_ = ~_008_;
  assign _010_ = ~current_state[1];
  assign _011_ = ~previous_state[1];
  assign _012_ = temp_critical ? _010_ : _011_;
  assign _013_ = _012_ | _056_;
  assign _014_ = door_open ? _010_ : _011_;
  assign _015_ = _058_ & ~(_014_);
  assign _016_ = _013_ & ~(_015_);
  assign _017_ = current_state[1] & ~(spin_done);
  assign _018_ = _017_ | door_open;
  assign _019_ = _080_ & ~(_018_);
  assign _020_ = _063_ & ~(_019_);
  assign _021_ = _016_ & ~(_020_);
  assign _022_ = current_state[1] & ~(drain_done);
  assign _023_ = _022_ | door_open;
  assign _024_ = _080_ & ~(_023_);
  assign _025_ = _067_ & ~(_024_);
  assign _026_ = wash_done | current_state[1];
  assign _027_ = _026_ | door_open;
  assign _028_ = _080_ & ~(_027_);
  assign _029_ = _068_ & ~(_028_);
  assign _030_ = _029_ | _025_;
  assign _031_ = water_fill | current_state[1];
  assign _032_ = _031_ | door_open;
  assign _033_ = _080_ & ~(_032_);
  assign _034_ = _066_ & ~(_033_);
  assign _035_ = _034_ | _030_;
  assign _036_ = _021_ & ~(_035_);
  assign _037_ = _071_ ? _009_ : _036_;
  assign next_state[1] = ~_037_;
  assign _038_ = _037_ | next_state[0];
  assign _039_ = _038_ | ~(next_state[2]);
  assign _040_ = _037_ | ~(next_state[0]);
  assign _041_ = next_state[2] & ~(_040_);
  assign _042_ = _039_ & ~(_041_);
  assign _000_ = _059_ & ~(_042_);
  assign _043_ = current_state[2] ? current_state[1] : _103_;
  assign _044_ = current_state[2] ? _055_ : _062_;
  assign _045_ = _044_ & ~(_058_);
  assign wash_motor = _045_ & _043_;
  assign heater = wash_motor & ~(temp_high);
  assign _046_ = _067_ | _063_;
  assign _047_ = _068_ | _066_;
  assign _048_ = _047_ | _046_;
  assign done = _045_ & ~(_048_);
  assign _049_ = current_state[1] ? _054_ : current_state[0];
  assign spin_motor = _045_ & ~(_049_);
  assign _050_ = _047_ | _064_;
  assign drain_pump = _045_ & ~(_050_);
  assign _051_ = _069_ | _064_;
  assign water_valve = _045_ & ~(_051_);
  (* src = "Washing_Mac_moore.v:98.5-108.8" *)
  always @(posedge clk, posedge reset)
    if (reset) previous_state[0] <= 1'h0;
    else if (_000_) previous_state[0] <= current_state[0];
  (* src = "Washing_Mac_moore.v:98.5-108.8" *)
  always @(posedge clk, posedge reset)
    if (reset) previous_state[1] <= 1'h0;
    else if (_000_) previous_state[1] <= current_state[1];
  (* src = "Washing_Mac_moore.v:98.5-108.8" *)
  always @(posedge clk, posedge reset)
    if (reset) previous_state[2] <= 1'h0;
    else if (_000_) previous_state[2] <= current_state[2];
  (* src = "Washing_Mac_moore.v:98.5-108.8" *)
  always @(posedge clk, posedge reset)
    if (reset) current_state[0] <= 1'h0;
    else current_state[0] <= next_state[0];
  (* src = "Washing_Mac_moore.v:98.5-108.8" *)
  always @(posedge clk, posedge reset)
    if (reset) current_state[1] <= 1'h0;
    else current_state[1] <= next_state[1];
  (* src = "Washing_Mac_moore.v:98.5-108.8" *)
  always @(posedge clk, posedge reset)
    if (reset) current_state[2] <= 1'h0;
    else current_state[2] <= next_state[2];
endmodule
